[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = false

[general]
live_config_reload = true
import = [
    # "~/.config/alacritty/themes/themes/github_light.toml"
]

[window]
decorations = "Full"
opacity = 0.95
decorations_theme_variant = "Dark"

[bell]
animation = "EaseOut"
duration = 150
color = "#4d7d6a"

[font]
# size = 10.0

[font.bold]
family = "DejaVu Sans Mono"
style = "Heavy"

[font.bold_italic]
family = "DejaVu Sans Mono"
style = "Heavy Italic"

[font.italic]
family = "DejaVu Sans Mono"
style = "Medium Italic"

[font.normal]
family = "DejaVu Sans Mono"
style = "Medium"
